// AUTO-GENERATED by .kani/gen_layer12_harnesses.py
// Do not edit manually. Regenerate with: python3 .kani/gen_layer12_harnesses.py
//
// Layer 1: No-panic verification — proves function doesn't panic for any valid input
// Layer 2: Bounds verification — proves output stays within expected range
//
// Run individual: cargo kani --harness <name>
// Run all: .kani/run_all.sh

// (non_snake_case allowed via parent module)

#[allow(unused_imports)]
use emcore::emViewAnimator::KineticState;
#[allow(unused_imports)]
use emcore::emPanel::Rect;
#[allow(unused_imports)]
use emcore::emTiling::Spacing;
#[allow(unused_imports)]
use emcore::emProcess::StartFlags;
#[allow(unused_imports)]
use emcore::emColor::emColor;
#[allow(unused_imports)]
use emcore::emLook::emLook;

#[cfg(kani)]
#[kani::proof]
fn kani_emATMatrix_AffineMatrix_new() {
    let mut p_a00: f64 = kani::any::<f64>();
    let mut p_a01: f64 = kani::any::<f64>();
    let mut p_a10: f64 = kani::any::<f64>();
    let mut p_a11: f64 = kani::any::<f64>();
    let mut p_a20: f64 = kani::any::<f64>();
    let mut p_a21: f64 = kani::any::<f64>();
    kani::assume(p_a00.is_finite());
    kani::assume(p_a01.is_finite());
    kani::assume(p_a10.is_finite());
    kani::assume(p_a11.is_finite());
    kani::assume(p_a20.is_finite());
    kani::assume(p_a21.is_finite());
    let _result = emcore::emATMatrix::AffineMatrix::new(p_a00, p_a01, p_a10, p_a11, p_a20, p_a21);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emATMatrix_AffineMatrix_translate() {
    let mut p_dx: f64 = kani::any::<f64>();
    let mut p_dy: f64 = kani::any::<f64>();
    kani::assume(p_dx.is_finite());
    kani::assume(p_dy.is_finite());
    let _result = emcore::emATMatrix::AffineMatrix::translate(p_dx, p_dy);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emATMatrix_AffineMatrix_scale() {
    let mut p_fac_x: f64 = kani::any::<f64>();
    let mut p_fac_y: f64 = kani::any::<f64>();
    kani::assume(p_fac_x.is_finite());
    kani::assume(p_fac_y.is_finite());
    let _result = emcore::emATMatrix::AffineMatrix::scale(p_fac_x, p_fac_y);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emATMatrix_AffineMatrix_scale_around() {
    let mut p_fac_x: f64 = kani::any::<f64>();
    let mut p_fac_y: f64 = kani::any::<f64>();
    let mut p_fix_x: f64 = kani::any::<f64>();
    let mut p_fix_y: f64 = kani::any::<f64>();
    kani::assume(p_fac_x.is_finite());
    kani::assume(p_fac_y.is_finite());
    kani::assume(p_fix_x.is_finite());
    kani::assume(p_fix_y.is_finite());
    let _result = emcore::emATMatrix::AffineMatrix::scale_around(p_fac_x, p_fac_y, p_fix_x, p_fix_y);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emATMatrix_AffineMatrix_rotate() {
    let mut p_angle: f64 = kani::any::<f64>();
    kani::assume(p_angle.is_finite());
    let _result = emcore::emATMatrix::AffineMatrix::rotate(p_angle);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emATMatrix_AffineMatrix_rotate_around() {
    let mut p_angle: f64 = kani::any::<f64>();
    let mut p_fix_x: f64 = kani::any::<f64>();
    let mut p_fix_y: f64 = kani::any::<f64>();
    kani::assume(p_angle.is_finite());
    kani::assume(p_fix_x.is_finite());
    kani::assume(p_fix_y.is_finite());
    let _result = emcore::emATMatrix::AffineMatrix::rotate_around(p_angle, p_fix_x, p_fix_y);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emATMatrix_AffineMatrix_shear() {
    let mut p_sh_x: f64 = kani::any::<f64>();
    let mut p_sh_y: f64 = kani::any::<f64>();
    kani::assume(p_sh_x.is_finite());
    kani::assume(p_sh_y.is_finite());
    let _result = emcore::emATMatrix::AffineMatrix::shear(p_sh_x, p_sh_y);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emATMatrix_AffineMatrix_shear_around() {
    let mut p_sh_x: f64 = kani::any::<f64>();
    let mut p_sh_y: f64 = kani::any::<f64>();
    let mut p_fix_x: f64 = kani::any::<f64>();
    let mut p_fix_y: f64 = kani::any::<f64>();
    kani::assume(p_sh_x.is_finite());
    kani::assume(p_sh_y.is_finite());
    kani::assume(p_fix_x.is_finite());
    kani::assume(p_fix_y.is_finite());
    let _result = emcore::emATMatrix::AffineMatrix::shear_around(p_sh_x, p_sh_y, p_fix_x, p_fix_y);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emClipRects_ClipRects_from_rect() {
    let mut p_x1: f64 = kani::any::<f64>();
    let mut p_y1: f64 = kani::any::<f64>();
    let mut p_x2: f64 = kani::any::<f64>();
    let mut p_y2: f64 = kani::any::<f64>();
    kani::assume(p_x1.is_finite());
    kani::assume(p_y1.is_finite());
    kani::assume(p_x2.is_finite());
    kani::assume(p_y2.is_finite());
    let _result = emcore::emClipRects::ClipRects::from_rect(p_x1, p_y1, p_x2, p_y2);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_rgba() {
    let mut p_r: u8 = kani::any::<u8>();
    let mut p_g: u8 = kani::any::<u8>();
    let mut p_b: u8 = kani::any::<u8>();
    let mut p_a: u8 = kani::any::<u8>();
    let _result = emcore::emColor::emColor::rgba(p_r, p_g, p_b, p_a);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_rgb() {
    let mut p_r: u8 = kani::any::<u8>();
    let mut p_g: u8 = kani::any::<u8>();
    let mut p_b: u8 = kani::any::<u8>();
    let _result = emcore::emColor::emColor::rgb(p_r, p_g, p_b);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetRed() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetRed();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetGreen() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetGreen();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetBlue() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetBlue();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetAlpha() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetAlpha();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetPacked() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetPacked();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetHSVA() {
    let mut p_h: f32 = kani::any::<f32>();
    let mut p_s: f32 = kani::any::<f32>();
    let mut p_v: f32 = kani::any::<f32>();
    kani::assume(p_h.is_finite());
    kani::assume(p_s.is_finite());
    kani::assume(p_v.is_finite());
    let _result = emcore::emColor::emColor::SetHSVA(p_h, p_s, p_v);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetHSV() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetHSV();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetLighted() {
    let self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let p_light: f32 = kani::any::<f32>();
    kani::assume(p_light.is_finite());
    let _result = self_val.GetLighted(p_light);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_blend() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_other = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_alpha: u8 = kani::any::<u8>();
    let _result = self_val.blend(p_other, p_alpha);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetAlpha() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_a: u8 = kani::any::<u8>();
    let _result = self_val.SetAlpha(p_a);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetBlended() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_other = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_t: f64 = kani::any::<f64>();
    kani::assume(p_t.is_finite());
    let _result = self_val.GetBlended(p_other, p_t);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_canvas_blend() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_source = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_canvas = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_alpha: u8 = kani::any::<u8>();
    let _result = self_val.canvas_blend(p_source, p_canvas, p_alpha);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetRed() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_r: u8 = kani::any::<u8>();
    let _result = self_val.SetRed(p_r);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetGreen() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_g: u8 = kani::any::<u8>();
    let _result = self_val.SetGreen(p_g);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetBlue() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_b: u8 = kani::any::<u8>();
    let _result = self_val.SetBlue(p_b);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_IsTotallyTransparent() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.IsTotallyTransparent();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_IsOpaque() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.IsOpaque();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_IsGrey() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.IsGrey();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetGrey() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetGrey();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetGrey() {
    let mut p_val: u8 = kani::any::<u8>();
    let _result = emcore::emColor::emColor::SetGrey(p_val);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetHue() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_h: f32 = kani::any::<f32>();
    kani::assume(p_h.is_finite());
    let _result = self_val.SetHue(p_h);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetSat() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_s: f32 = kani::any::<f32>();
    kani::assume(p_s.is_finite());
    let _result = self_val.SetSat(p_s);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_SetVal() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_v: f32 = kani::any::<f32>();
    kani::assume(p_v.is_finite());
    let _result = self_val.SetVal(p_v);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emColor_emColor_GetTransparented() {
    let mut self_val = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_amount: f64 = kani::any::<f64>();
    kani::assume(p_amount.is_finite());
    let _result = self_val.GetTransparented(p_amount);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emImage_emImage_new() {
    let mut p_width: u32 = kani::any::<u32>();
    let mut p_height: u32 = kani::any::<u32>();
    let mut p_channel_count: u8 = kani::any::<u8>();
    let _result = emcore::emImage::emImage::new(p_width, p_height, p_channel_count);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emImage_emImage_is_channel_count_paintable() {
    let mut p_channel_count: u8 = kani::any::<u8>();
    let _result = emcore::emImage::emImage::is_channel_count_paintable(p_channel_count);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emLinearLayout_emLinearLayout_adaptive() {
    let mut p_tallness_threshold: f64 = kani::any::<f64>();
    kani::assume(p_tallness_threshold.is_finite());
    let _result = emcore::emLinearLayout::emLinearLayout::adaptive(p_tallness_threshold);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emLook_emLook_border_tint() {
    let mut self_val = emLook { bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()) };
    let _result = self_val.border_tint();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emLook_emLook_focus_tint() {
    let mut self_val = emLook { bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()) };
    let _result = self_val.focus_tint();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emLook_emLook_disabled_fg() {
    let mut self_val = emLook { bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()) };
    let _result = self_val.disabled_fg();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emLook_emLook_button_hover() {
    let mut self_val = emLook { bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()) };
    let _result = self_val.button_hover();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emLook_emLook_button_pressed() {
    let mut self_val = emLook { bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), button_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), input_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_bg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_fg_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), output_hl_color: emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()) };
    let _result = self_val.button_pressed();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emProcess_StartFlags_contains() {
    let mut self_val = emcore::emProcess::StartFlags::empty();
    let mut p_other = emcore::emProcess::StartFlags::empty();
    let _result = self_val.contains(p_other);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRecRecTypes_emColorRec_new() {
    let mut p_default_value = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_have_alpha: bool = kani::any::<bool>();
    let _result = emcore::emRecRecTypes::emColorRec::new(p_default_value, p_have_alpha);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRecRecTypes_emColorRec_GetRec() {
    let mut self_val = emcore::emRecRecTypes::emColorRec::new(emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), kani::any());
    let _result = self_val.GetRec();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRecRecTypes_emColorRec_Set() {
    let mut self_val = emcore::emRecRecTypes::emColorRec::new(emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), kani::any());
    let mut p_value = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.Set(p_value);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRecRecTypes_emColorRec_SetToDefault() {
    let mut self_val = emcore::emRecRecTypes::emColorRec::new(emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), kani::any());
    let _result = self_val.SetToDefault();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRecRecTypes_emColorRec_IsSetToDefault() {
    let mut self_val = emcore::emRecRecTypes::emColorRec::new(emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), kani::any());
    let _result = self_val.IsSetToDefault();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRecRecTypes_emColorRec_HaveAlpha() {
    let mut self_val = emcore::emRecRecTypes::emColorRec::new(emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any()), kani::any());
    let _result = self_val.HaveAlpha();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRecRecTypes_emColorRec_ToRecStruct() {
    let mut p_color = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_have_alpha: bool = kani::any::<bool>();
    let _result = emcore::emRecRecTypes::emColorRec::ToRecStruct(p_color, p_have_alpha);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRenderThreadPool_emRenderThreadPool_new() {
    let mut p_max_render_threads: i32 = kani::any::<i32>();
    let _result = emcore::emRenderThreadPool::emRenderThreadPool::new(p_max_render_threads);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRenderThreadPool_emRenderThreadPool_GetThreadCount() {
    let mut self_val = emcore::emRenderThreadPool::emRenderThreadPool::new(kani::any());
    let _result = self_val.GetThreadCount();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emRenderThreadPool_emRenderThreadPool_UpdateThreadCount() {
    let mut self_val = emcore::emRenderThreadPool::emRenderThreadPool::new(kani::any());
    let mut p_max_render_threads: i32 = kani::any::<i32>();
    let _result = self_val.UpdateThreadCount(p_max_render_threads);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emStd1_emEnableDLog() {
    let mut p_enable: bool = kani::any::<bool>();
    let _result = emcore::emStd1::emEnableDLog(p_enable);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emStd1_emSetFatalErrorGraphical() {
    let mut p_enable: bool = kani::any::<bool>();
    let _result = emcore::emStd1::emSetFatalErrorGraphical(p_enable);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emStroke_emStroke_new() {
    let mut p_color = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_width: f64 = kani::any::<f64>();
    kani::assume(p_width.is_finite());
    let _result = emcore::emStroke::emStroke::new(p_color, p_width);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emTexture_emTexture_GetColor() {
    let mut p_c = emcore::emColor::emColor::rgba(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = emcore::emTexture::emTexture::GetColor(p_c);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emTiling_Spacing_uniform() {
    let mut p_margin: f64 = kani::any::<f64>();
    let mut p_inner: f64 = kani::any::<f64>();
    kani::assume(p_margin.is_finite());
    kani::assume(p_inner.is_finite());
    let _result = emcore::emTiling::Spacing::uniform(p_margin, p_inner);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emTiling_Spacing_clamped() {
    let mut self_val = Spacing { inner_h: kani::any::<f64>(), inner_v: kani::any::<f64>(), margin_left: kani::any::<f64>(), margin_right: kani::any::<f64>(), margin_top: kani::any::<f64>(), margin_bottom: kani::any::<f64>() };
    let _result = self_val.clamped();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_new() {
    let mut p_velocity_x: f64 = kani::any::<f64>();
    let mut p_velocity_y: f64 = kani::any::<f64>();
    let mut p_velocity_z: f64 = kani::any::<f64>();
    let mut p_friction: f64 = kani::any::<f64>();
    kani::assume(p_velocity_x.is_finite());
    kani::assume(p_velocity_y.is_finite());
    kani::assume(p_velocity_z.is_finite());
    kani::assume(p_friction.is_finite());
    let _result = emcore::emViewAnimator::emKineticViewAnimator::new(p_velocity_x, p_velocity_y, p_velocity_z, p_friction);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_SetVelocity() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_vx: f64 = kani::any::<f64>();
    let mut p_vy: f64 = kani::any::<f64>();
    let mut p_vz: f64 = kani::any::<f64>();
    kani::assume(p_vx.is_finite());
    kani::assume(p_vy.is_finite());
    kani::assume(p_vz.is_finite());
    let _result = self_val.SetVelocity(p_vx, p_vy, p_vz);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_GetVelocity() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetVelocity();
    assert!(_result.0.is_finite(), "non-finite result.0");
    assert!(_result.1.is_finite(), "non-finite result.1");
    assert!(_result.2.is_finite(), "non-finite result.2");
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_GetAbsVelocity() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetAbsVelocity();
    // Layer 2: finite output from finite inputs
    assert!(_result.is_finite(), "non-finite result");
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_SetFrictionEnabled() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_enabled: bool = kani::any::<bool>();
    let _result = self_val.SetFrictionEnabled(p_enabled);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_IsFrictionEnabled() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.IsFrictionEnabled();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_SetFriction() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_friction: f64 = kani::any::<f64>();
    kani::assume(p_friction.is_finite());
    let _result = self_val.SetFriction(p_friction);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_GetFriction() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.GetFriction();
    // Layer 2: finite output from finite inputs
    assert!(_result.is_finite(), "non-finite result");
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_extract_kinetic_state() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let _result = self_val.extract_kinetic_state();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emKineticViewAnimator_inject_kinetic_state() {
    let mut self_val = emcore::emViewAnimator::emKineticViewAnimator::new(kani::any(), kani::any(), kani::any(), kani::any());
    let mut p_state = KineticState { vx: kani::any::<f64>(), vy: kani::any::<f64>(), vz: kani::any::<f64>(), zoom_fix_centered: kani::any::<bool>(), zoom_fix_x: kani::any::<f64>(), zoom_fix_y: kani::any::<f64>() };
    let _result = self_val.inject_kinetic_state(p_state);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSpeedingViewAnimator_new() {
    let mut p_friction: f64 = kani::any::<f64>();
    kani::assume(p_friction.is_finite());
    let _result = emcore::emViewAnimator::emSpeedingViewAnimator::new(p_friction);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSpeedingViewAnimator_SetTargetVelocity() {
    let mut self_val = emcore::emViewAnimator::emSpeedingViewAnimator::new(kani::any());
    let mut p_vx: f64 = kani::any::<f64>();
    let mut p_vy: f64 = kani::any::<f64>();
    let mut p_vz: f64 = kani::any::<f64>();
    kani::assume(p_vx.is_finite());
    kani::assume(p_vy.is_finite());
    kani::assume(p_vz.is_finite());
    let _result = self_val.SetTargetVelocity(p_vx, p_vy, p_vz);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSpeedingViewAnimator_release() {
    let mut self_val = emcore::emViewAnimator::emSpeedingViewAnimator::new(kani::any());
    let _result = self_val.release();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSpeedingViewAnimator_SetAcceleration() {
    let mut self_val = emcore::emViewAnimator::emSpeedingViewAnimator::new(kani::any());
    let mut p_accel: f64 = kani::any::<f64>();
    kani::assume(p_accel.is_finite());
    let _result = self_val.SetAcceleration(p_accel);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSpeedingViewAnimator_SetReverseAcceleration() {
    let mut self_val = emcore::emViewAnimator::emSpeedingViewAnimator::new(kani::any());
    let mut p_accel: f64 = kani::any::<f64>();
    kani::assume(p_accel.is_finite());
    let _result = self_val.SetReverseAcceleration(p_accel);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSpeedingViewAnimator_inner() {
    let mut self_val = emcore::emViewAnimator::emSpeedingViewAnimator::new(kani::any());
    let _result = self_val.inner();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSpeedingViewAnimator_inner_mut() {
    let mut self_val = emcore::emViewAnimator::emSpeedingViewAnimator::new(kani::any());
    let _result = self_val.inner_mut();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emVisitingViewAnimator_new() {
    let mut p_target_x: f64 = kani::any::<f64>();
    let mut p_target_y: f64 = kani::any::<f64>();
    let mut p_target_a: f64 = kani::any::<f64>();
    let mut p__speed: f64 = kani::any::<f64>();
    kani::assume(p_target_x.is_finite());
    kani::assume(p_target_y.is_finite());
    kani::assume(p_target_a.is_finite());
    kani::assume(p__speed.is_finite());
    let _result = emcore::emViewAnimator::emVisitingViewAnimator::new(p_target_x, p_target_y, p_target_a, p__speed);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSwipingViewAnimator_new() {
    let mut p_friction: f64 = kani::any::<f64>();
    kani::assume(p_friction.is_finite());
    let _result = emcore::emViewAnimator::emSwipingViewAnimator::new(p_friction);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSwipingViewAnimator_SetGripped() {
    let mut self_val = emcore::emViewAnimator::emSwipingViewAnimator::new(kani::any());
    let mut p_gripped: bool = kani::any::<bool>();
    let _result = self_val.SetGripped(p_gripped);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSwipingViewAnimator_IsGripped() {
    let mut self_val = emcore::emViewAnimator::emSwipingViewAnimator::new(kani::any());
    let _result = self_val.IsGripped();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSwipingViewAnimator_MoveGrip() {
    let mut self_val = emcore::emViewAnimator::emSwipingViewAnimator::new(kani::any());
    let mut p_dimension: usize = kani::any::<usize>();
    let mut p_distance: f64 = kani::any::<f64>();
    kani::assume(p_distance.is_finite());
    let _result = self_val.MoveGrip(p_dimension, p_distance);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSwipingViewAnimator_SetSpringConstant() {
    let mut self_val = emcore::emViewAnimator::emSwipingViewAnimator::new(kani::any());
    let mut p_k: f64 = kani::any::<f64>();
    kani::assume(p_k.is_finite());
    let _result = self_val.SetSpringConstant(p_k);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSwipingViewAnimator_GetAbsSpringExtension() {
    let mut self_val = emcore::emViewAnimator::emSwipingViewAnimator::new(kani::any());
    let _result = self_val.GetAbsSpringExtension();
    // Layer 2: finite output from finite inputs
    assert!(_result.is_finite(), "non-finite result");
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSwipingViewAnimator_inner() {
    let mut self_val = emcore::emViewAnimator::emSwipingViewAnimator::new(kani::any());
    let _result = self_val.inner();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emSwipingViewAnimator_inner_mut() {
    let mut self_val = emcore::emViewAnimator::emSwipingViewAnimator::new(kani::any());
    let _result = self_val.inner_mut();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emMagneticViewAnimator_new() {
    let _result = emcore::emViewAnimator::emMagneticViewAnimator::new();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emMagneticViewAnimator_set_radius_factor() {
    let mut self_val = emcore::emViewAnimator::emMagneticViewAnimator::new();
    let p_f: f64 = kani::any::<f64>();
    kani::assume(p_f.is_finite());
    self_val.set_radius_factor(p_f);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emMagneticViewAnimator_set_speed_factor() {
    let mut self_val = emcore::emViewAnimator::emMagneticViewAnimator::new();
    let p_f: f64 = kani::any::<f64>();
    kani::assume(p_f.is_finite());
    self_val.set_speed_factor(p_f);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewAnimator_emMagneticViewAnimator_is_magnetism_active() {
    let self_val = emcore::emViewAnimator::emMagneticViewAnimator::new();
    let _result = self_val.is_magnetism_active();
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewRenderer_SoftwareCompositor_new() {
    let mut p_width: u32 = kani::any::<u32>();
    let mut p_height: u32 = kani::any::<u32>();
    let _result = emcore::emViewRenderer::SoftwareCompositor::new(p_width, p_height);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emViewRendererTileCache_TileCache_new() {
    let mut p_viewport_width: u32 = kani::any::<u32>();
    let mut p_viewport_height: u32 = kani::any::<u32>();
    let mut p_max_tiles: usize = kani::any::<usize>();
    let _result = emcore::emViewRendererTileCache::TileCache::new(p_viewport_width, p_viewport_height, p_max_tiles);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emWindowPlatform_uninhibit_screensaver() {
    let mut p_cookie: u32 = kani::any::<u32>();
    let _result = emcore::emWindowPlatform::uninhibit_screensaver(p_cookie);
}

#[cfg(kani)]
#[kani::proof]
fn kani_emWindowPlatform_uninhibit_screensaver_157() {
    let mut p__cookie: u32 = kani::any::<u32>();
    let _result = emcore::emWindowPlatform::uninhibit_screensaver(p__cookie);
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_from_raw() {
    let mut p_raw: i32 = kani::any::<i32>();
    let _result = emcore::emPainter::Fixed12::from_raw(p_raw);
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_raw() {
    let mut self_val = emcore::emPainter::Fixed12::from_raw(kani::any());
    let _result = self_val.raw();
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_from_f64() {
    let mut p_v: f64 = kani::any::<f64>();
    kani::assume(p_v.is_finite());
    let _result = emcore::emPainter::Fixed12::from_f64(p_v);
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_from_i32() {
    let mut p_v: i32 = kani::any::<i32>();
    let _result = emcore::emPainter::Fixed12::from_i32(p_v);
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_to_f64() {
    let mut self_val = emcore::emPainter::Fixed12::from_raw(kani::any());
    let _result = self_val.to_f64();
    // Layer 2: finite output from finite inputs
    assert!(_result.is_finite(), "non-finite result");
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_to_i32() {
    let mut self_val = emcore::emPainter::Fixed12::from_raw(kani::any());
    let _result = self_val.to_i32();
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_frac() {
    let mut self_val = emcore::emPainter::Fixed12::from_raw(kani::any());
    let _result = self_val.frac();
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_floor() {
    let mut self_val = emcore::emPainter::Fixed12::from_raw(kani::any());
    let _result = self_val.floor();
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_ceil() {
    let mut self_val = emcore::emPainter::Fixed12::from_raw(kani::any());
    let _result = self_val.ceil();
}

#[cfg(kani)]
#[kani::proof]
fn kani_fixed_Fixed12_round() {
    let mut self_val = emcore::emPainter::Fixed12::from_raw(kani::any());
    let _result = self_val.round();
}

#[cfg(kani)]
#[kani::proof]
fn kani_rect_Rect_new() {
    let mut p_x: f64 = kani::any::<f64>();
    let mut p_y: f64 = kani::any::<f64>();
    let mut p_w: f64 = kani::any::<f64>();
    let mut p_h: f64 = kani::any::<f64>();
    kani::assume(p_x.is_finite());
    kani::assume(p_y.is_finite());
    kani::assume(p_w.is_finite());
    kani::assume(p_h.is_finite());
    let _result = emcore::emPanel::Rect::new(p_x, p_y, p_w, p_h);
}

#[cfg(kani)]
#[kani::proof]
fn kani_rect_Rect_intersects() {
    let mut self_val = Rect { x: kani::any::<f64>(), y: kani::any::<f64>(), w: kani::any::<f64>(), h: kani::any::<f64>() };
    let mut p_other = Rect { x: kani::any::<f64>(), y: kani::any::<f64>(), w: kani::any::<f64>(), h: kani::any::<f64>() };
    let _result = self_val.intersects(&p_other);
}

#[cfg(kani)]
#[kani::proof]
fn kani_rect_Rect_intersection() {
    let mut self_val = Rect { x: kani::any::<f64>(), y: kani::any::<f64>(), w: kani::any::<f64>(), h: kani::any::<f64>() };
    let mut p_other = Rect { x: kani::any::<f64>(), y: kani::any::<f64>(), w: kani::any::<f64>(), h: kani::any::<f64>() };
    let _result = self_val.intersection(&p_other);
}

#[cfg(kani)]
#[kani::proof]
fn kani_rect_Rect_contains_point() {
    let mut self_val = Rect { x: kani::any::<f64>(), y: kani::any::<f64>(), w: kani::any::<f64>(), h: kani::any::<f64>() };
    let mut p_px: f64 = kani::any::<f64>();
    let mut p_py: f64 = kani::any::<f64>();
    kani::assume(p_px.is_finite());
    kani::assume(p_py.is_finite());
    let _result = self_val.contains_point(p_px, p_py);
}

#[cfg(kani)]
#[kani::proof]
fn kani_rect_Rect_area() {
    let mut self_val = Rect { x: kani::any::<f64>(), y: kani::any::<f64>(), w: kani::any::<f64>(), h: kani::any::<f64>() };
    let _result = self_val.area();
    // Layer 2: finite output from finite inputs
    assert!(_result.is_finite(), "non-finite result");
}

